### ISSUE TITLE
Missing module error 

### ISSUE THREAD

**Issue by trdvangraft** [Azure/ccodashboard#229]
**Describe the bug**

**To Reproduce**
1. Follow the Governance dashboard setup guideline
2. Download the custom connector
3.  Install the connector in the specified folder

**Expected behavior**
Once the .mez file is located at the 'C:\Users\%username%\Documents\Power BI Desktop\Custom Connectors' it should be discoverable by the `Get Data` functionality of powerbi but it isnt

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: DNA
 - Version: 10

**Comment by trdvangraft** [comment]
I fixed this bug by creating a folder in `C:\Users\%username%\Documents\Microsoft Power BI Desktop\Custom Connectors` I wonder if this is an isolated case or that other people are having to specify a similar folder

**Comment by dinesh-mna** [comment]
I am also facing issue as 
![image](https://user-images.githubusercontent.com/102744444/161072970-9c83d0ab-52e4-488c-87e1-58044ae8139a.png)


![image](https://user-images.githubusercontent.com/102744444/161073415-a51883d2-5b77-4336-a0e2-62d6303c3fc8.png)

**Comment by trdvangraft** [comment]
> I am also facing issue as ![image](https://user-images.githubusercontent.com/102744444/161072970-9c83d0ab-52e4-488c-87e1-58044ae8139a.png)
> 
> ![image](https://user-images.githubusercontent.com/102744444/161073415-a51883d2-5b77-4336-a0e2-62d6303c3fc8.png)

Wher you able to fix this by changing the Power Bi Desktop folder name to Microsoft Power BI Desktop?

**Comment by josunefon** [comment]
your're right @trdvangraft if there's no folder you need to create it, @dinesh-mna is your problem fixed?

**Comment by josunefon** [comment]
Incident closed due to lack of response, please open a new one if problems persist.

**Comment by Tsholofelom** [comment]
Hi Everyone 
I am getting the same error,
I followed @trdvangraft  suggestion and created the "C:\Users\%username%\Documents\Microsoft Power BI Desktop\Custom Connectors" folder .
Issue still persists 
<img width="385" alt="Error3" src="https://github.com/Azure/CCOInsights/assets/31691532/248393b1-d579-4370-a626-10cbba429a27">
